project_name: healthchecker
release:
  github:
    owner: tufitko
    name: healthchecker

builds:
  - id: healthchecker
    binary: healthchecker
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - healthchecker
    image_templates:
      - "tufitko/healthchecker:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx
  - goos: linux
    goarch: arm64
    ids:
      - healthchecker
    image_templates:
      - "tufitko/healthchecker:v{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
    use: buildx
docker_manifests:
  - name_template: tufitko/healthchecker:v{{ .Version }}
    image_templates:
      - tufitko/healthchecker:v{{ .Version }}-amd64
      - tufitko/healthchecker:v{{ .Version }}-arm64
